-r base.in
async_generator; python_version < '3.7'
mypy
tox
coverage
flake8
flake8_docstrings
mock
# pytest-black is currently causing an exception with pytest >= 8
pytest < 8
pytest-asyncio
pytest-black
pytest-cov
pytest-mock
